services:
  app:
    container_name: rakutter_app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app/:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - 3000:3000
    depends_on:
      - api
      - db

  api:
    image: rakutter-api:latest
    build:
      context: ./api
    volumes:
      - ./api/:/app
    command: deno task start
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      - db

  db:
    container_name: rakutter_db
    image: mysql:8.1.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rakutter

volumes:
  node_modules:
  mysql_data:
