version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - ./:/usr/src/app # ローカルをコンテナ内にマウント
      - node_modules:/usr/src/app/node_modules # 名前付きボリュームからマウント
    command: sh -c "npm run dev -- --host"
    ports:
      - '${APP_PORT:-3000}:5173'
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api/:/app
    command: deno run --allow-net ./src/main.ts
    ports:
      - '${API_PORT:-8000}:8000'

volumes:
  node_modules:
