version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - ./:/usr/src/app # ローカルをコンテナ内にマウント
      - node_modules:/usr/src/app/node_modules # 名前付きボリュームからマウント
    command: sh -c "npm run dev -- --host"
    ports:
      - "${APP_PORT:-3000}:5173"
    stdin_open: true
    tty: true

volumes:
  node_modules:
