version: "3.9"
services:
  app:
    container_name: rakutter_app
    build:
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - ./app/:/usr/src/app # ローカルをコンテナ内にマウント
      - node_modules:/usr/src/app/node_modules # 名前付きボリュームからマウント
    command: sh -c "npm run dev -- --host"
    ports:
      - "${APP_PORT:-3000}:5173"
    depends_on:
      - api
      - db

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api/:/app
    command: deno run --allow-net ./src/main.ts
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      - db

  db:
    container_name: rakutter_db
    image: mysql:8.1.0
    restart: always
    ports:
      - 5432:5432
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rakutter

volumes:
  node_modules:
  mysql_data:
