name: ApiLintCI

on:
  push:
    paths:
      - "api/**/*"

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: api/lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.38.2

      - name: lint
        run: deno lint

  format:
    name: api/format
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.38.2

      - name: format
        run: deno task format:check
