name: lintCI

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  app-check-lint:
    name: app/check-lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
          cache: npm
          cache-dependency-path: ./app/package-lock.json

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: lint
        run: npm run lint
  api-check-lint:
    name: api/check-lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.15.3

      - name: lint
        run: deno lint
