name: lintCI

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: ./app/package-lock.json

      - name: install
        run: npm ci

      - name: lint
        run: npm run lint
